### ISSUE TITLE
[BUG] bottom navigation 관련

### ISSUE THREAD

**Issue by gayeon00** [APPSCHOOL2-Android/FinalProject-PetPal#11]
## 버그 설명
마이페이지에서 하위 메뉴를 들어간 상태에서 다른 바텀네비 탭을 눌렀다가, 다시 마이페이지 탭을 누르면
마이페이지 처음 화면으로 가는게 아니라 전에 있던, 하위메뉴로 이동하고, 바텀네비에 선택 표시도 안되네요

## 발동 조건
1. 마이페이지 진입
2. 하위메뉴 아무거나 진입
3. 다른 바텀 네비 둘러서 이동
4. 다시 바텀네비 통해 마이페이지 진입시도

## 원하는 결과물
마이페이지 바텀 네비를 누르면 어느 상황이든 마이페이지 화면만 나왔으면 좋겠군요

## 스크린샷
![바텀네비 에러](https://github.com/APPSCHOOL2-Android/FinalProject-PetPal/assets/68911884/0c682e8a-a14c-4da3-ab15-92ff65396348)

## ETC
기타사항

**Comment by kimjinsub1217** [comment]
MainFragment에 있는 코드를  https://stackoverflow.com/questions/71089052/android-navigation-component-bottomnavigationviews-selected-tab-icon-is-not-u  여기서 맨 위에 나와있는 솔루션으로 바꾸고 한번 해보시겠어요?

**Comment by kimjinsub1217** [comment]
```
 fragmentMainBinding.run {
            bottomNavigation.run {
                setupWithNavController(navController)
            } 
```

이 코드에서

```
   bottomNavigation.setOnItemSelectedListener { item ->

                NavigationUI.onNavDestinationSelected(item, navController)

                return@setOnItemSelectedListener true
```
이 코드로 변경 후 확인해주세요!
