### ISSUE TITLE
[BUG] 탭 이동 애니메이션 속도

### ISSUE THREAD

**Issue by gayeon00** [APPSCHOOL2-Android/FinalProject-PetPal#79]
## 버그 설명
탭 이동시 나가고 들어오는 애니메이션의 속도가 다른건지 좀 밀리는 느낌입니다

## 스크린샷
https://github.com/APPSCHOOL2-Android/FinalProject-PetPal/assets/68911884/a0af8abe-e994-473a-99d7-c1874e3642a6

## ETC
기타사항

**Comment by kimjinsub1217** [comment]
진입하는 애니메이션 700 나가는 애니메이션 500 으로 설정되어 있어서 그런 거 같아요. 애니메이션이 잘 보이게 조금 느리게 설정했는데 속도 조절하고 pr 올릴게요
